name: Publish Site

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          yarn install
          yarn build
          git rev-parse --short HEAD >> commit-sha
          cd build
          git init
          git remote add origin https://github.com/JoeZwet/joezwet.dev.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git branch -m master gh-pages
          git commit -m "chore: publish $(< ../commit-sha)"
          git push -u origin gh-pages -f